#!/bin/zsh

source ~/.zshrc
cmd=$1
expr=$2
tmr=$3
echo Command:   $cmd
echo Expression:   $exp
echo Every:     $tmr
while :; 
    do 
        #ls -al "$expr"
        $(cmd) "$expr"
        echo `date`;
        sleep "$tmr" 
    done
